# Generated by Django 3.2.8 on 2022-10-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='like',
        ),
        migrations.AddField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
